from sqlalchemy.sql import func
from flask import Flask, render_template, request, url_for, redirect, flash, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin, login_user, LoginManager, login_required, current_user, logout_user
import os
app = Flask(__name__)

app.config['SECRET_KEY'] = 'randomkeybestkey'
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get(
    "DATABASE_URL", "sqlite:///database.db")
#
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)


def create_db():
    class User(UserMixin, db.Model):
        id = db.Column(db.Integer, primary_key=True)
        email = db.Column(db.String(100), unique=True)
        password = db.Column(db.String(100))
        name = db.Column(db.String(1000))
        permission = db.Column(db.String(100))
        created_at = db.Column(db.DateTime(timezone=True),
                               server_default=func.now())
        # clube_id = db.Column(db.Integer)

    class Campo(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(100))
        tee_saida_1 = db.Column(db.String(100))
        slope_1 = db.Column(db.Integer)
        course_rating_1 = db.Column(db.Float)
        b1_par_1 = db.Column(db.Integer)
        b2_par_1 = db.Column(db.Integer)
        b3_par_1 = db.Column(db.Integer)
        b4_par_1 = db.Column(db.Integer)
        b5_par_1 = db.Column(db.Integer)
        b6_par_1 = db.Column(db.Integer)
        b7_par_1 = db.Column(db.Integer)
        b8_par_1 = db.Column(db.Integer)
        b9_par_1 = db.Column(db.Integer)
        b10_par_1 = db.Column(db.Integer)
        b11_par_1 = db.Column(db.Integer)
        b12_par_1 = db.Column(db.Integer)
        b13_par_1 = db.Column(db.Integer)
        b14_par_1 = db.Column(db.Integer)
        b15_par_1 = db.Column(db.Integer)
        b16_par_1 = db.Column(db.Integer)
        b17_par_1 = db.Column(db.Integer)
        b18_par_1 = db.Column(db.Integer)
        b1_hcp_stroke_1 = db.Column(db.Integer)
        b2_hcp_stroke_1 = db.Column(db.Integer)
        b3_hcp_stroke_1 = db.Column(db.Integer)
        b4_hcp_stroke_1 = db.Column(db.Integer)
        b5_hcp_stroke_1 = db.Column(db.Integer)
        b6_hcp_stroke_1 = db.Column(db.Integer)
        b7_hcp_stroke_1 = db.Column(db.Integer)
        b8_hcp_stroke_1 = db.Column(db.Integer)
        b9_hcp_stroke_1 = db.Column(db.Integer)
        b10_hcp_stroke_1 = db.Column(db.Integer)
        b11_hcp_stroke_1 = db.Column(db.Integer)
        b12_hcp_stroke_1 = db.Column(db.Integer)
        b13_hcp_stroke_1 = db.Column(db.Integer)
        b14_hcp_stroke_1 = db.Column(db.Integer)
        b15_hcp_stroke_1 = db.Column(db.Integer)
        b16_hcp_stroke_1 = db.Column(db.Integer)
        b17_hcp_stroke_1 = db.Column(db.Integer)
        b18_hcp_stroke_1 = db.Column(db.Integer)
        b1_distance_1 = db.Column(db.Integer)
        b2_distance_1 = db.Column(db.Integer)
        b3_distance_1 = db.Column(db.Integer)
        b4_distance_1 = db.Column(db.Integer)
        b5_distance_1 = db.Column(db.Integer)
        b6_distance_1 = db.Column(db.Integer)
        b7_distance_1 = db.Column(db.Integer)
        b8_distance_1 = db.Column(db.Integer)
        b9_distance_1 = db.Column(db.Integer)
        b10_distance_1 = db.Column(db.Integer)
        b11_distance_1 = db.Column(db.Integer)
        b12_distance_1 = db.Column(db.Integer)
        b13_distance_1 = db.Column(db.Integer)
        b14_distance_1 = db.Column(db.Integer)
        b15_distance_1 = db.Column(db.Integer)
        b16_distance_1 = db.Column(db.Integer)
        b17_distance_1 = db.Column(db.Integer)
        b18_distance_1 = db.Column(db.Integer)
        tee_saida_2 = db.Column(db.String(100))
        slope_2 = db.Column(db.Float(100))
        corse_rating_2 = db.Column(db.Float(100))
        b1_par_2 = db.Column(db.Integer)
        b2_par_2 = db.Column(db.Integer)
        b3_par_2 = db.Column(db.Integer)
        b4_par_2 = db.Column(db.Integer)
        b5_par_2 = db.Column(db.Integer)
        b6_par_2 = db.Column(db.Integer)
        b7_par_2 = db.Column(db.Integer)
        b8_par_2 = db.Column(db.Integer)
        b9_par_2 = db.Column(db.Integer)
        b10_par_2 = db.Column(db.Integer)
        b11_par_2 = db.Column(db.Integer)
        b12_par_2 = db.Column(db.Integer)
        b13_par_2 = db.Column(db.Integer)
        b14_par_2 = db.Column(db.Integer)
        b15_par_2 = db.Column(db.Integer)
        b16_par_2 = db.Column(db.Integer)
        b17_par_2 = db.Column(db.Integer)
        b18_par_2 = db.Column(db.Integer)
        b1_hcp_stroke_2 = db.Column(db.Integer)
        b2_hcp_stroke_2 = db.Column(db.Integer)
        b3_hcp_stroke_2 = db.Column(db.Integer)
        b4_hcp_stroke_2 = db.Column(db.Integer)
        b5_hcp_stroke_2 = db.Column(db.Integer)
        b6_hcp_stroke_2 = db.Column(db.Integer)
        b7_hcp_stroke_2 = db.Column(db.Integer)
        b8_hcp_stroke_2 = db.Column(db.Integer)
        b9_hcp_stroke_2 = db.Column(db.Integer)
        b10_hcp_stroke_2 = db.Column(db.Integer)
        b11_hcp_stroke_2 = db.Column(db.Integer)
        b12_hcp_stroke_2 = db.Column(db.Integer)
        b13_hcp_stroke_2 = db.Column(db.Integer)
        b14_hcp_stroke_2 = db.Column(db.Integer)
        b15_hcp_stroke_2 = db.Column(db.Integer)
        b16_hcp_stroke_2 = db.Column(db.Integer)
        b17_hcp_stroke_2 = db.Column(db.Integer)
        b18_hcp_stroke_2 = db.Column(db.Integer)
        b1_distance_2 = db.Column(db.Integer)
        b2_distance_2 = db.Column(db.Integer)
        b3_distance_2 = db.Column(db.Integer)
        b4_distance_2 = db.Column(db.Integer)
        b5_distance_2 = db.Column(db.Integer)
        b6_distance_2 = db.Column(db.Integer)
        b7_distance_2 = db.Column(db.Integer)
        b8_distance_2 = db.Column(db.Integer)
        b9_distance_2 = db.Column(db.Integer)
        b10_distance_2 = db.Column(db.Integer)
        b11_distance_2 = db.Column(db.Integer)
        b12_distance_2 = db.Column(db.Integer)
        b13_distance_2 = db.Column(db.Integer)
        b14_distance_2 = db.Column(db.Integer)
        b15_distance_2 = db.Column(db.Integer)
        b16_distance_2 = db.Column(db.Integer)
        b17_distance_2 = db.Column(db.Integer)
        b18_distance_2 = db.Column(db.Integer)

    class Player(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(1000))
        email = db.Column(db.String(100))
        hcp_id = db.Column(db.Integer, unique=True)
        hcp_index = db.Column(db.Float)
        hcp_qn = db.Column(db.Float)
        pt_ranking = db.Column(db.Float)
        cat = db.Column(db.String(10))
        juv = db.Column(db.String(10))
        senior = db.Column(db.String(10))

    class Torneios(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        name = db.Column(db.String(1000))
        date = db.Column(db.String(100))
        type = db.Column(db.String(100))
        cat = db.Column(db.String(100))

    class Torneio_atual(db.Model):
        id = db.Column(db.Integer, primary_key=True)
        torneio_id = db.Column(db.String(100))
        pago = db.Column(db.String(100))
        jogador = db.Column(db.String(100))
        hcp = db.Column(db.String(100))
        cat = db.Column(db.String(100))
        juv = db.Column(db.String(100))
        senior = db.Column(db.String(100))
        b_saida = db.Column(db.String(100))
        b1 = db.Column(db.Integer)
        b2 = db.Column(db.Integer)
        b3 = db.Column(db.Integer)
        b4 = db.Column(db.Integer)
        b5 = db.Column(db.Integer)
        b6 = db.Column(db.Integer)
        b7 = db.Column(db.Integer)
        b8 = db.Column(db.Integer)
        b9 = db.Column(db.Integer)
        b10 = db.Column(db.Integer)
        b11 = db.Column(db.Integer)
        b12 = db.Column(db.Integer)
        b13 = db.Column(db.Integer)
        b14 = db.Column(db.Integer)
        b15 = db.Column(db.Integer)
        b16 = db.Column(db.Integer)
        b17 = db.Column(db.Integer)
        b18 = db.Column(db.Integer)
        v1_gross = db.Column(db.Integer)
        v2_gross = db.Column(db.Integer)
        total_gross = db.Column(db.Integer)
        total_net = db.Column(db.Integer)
        v2_net = db.Column(db.Integer)
        ult_6b_net = db.Column(db.Integer)
        ult_3b_net = db.Column(db.Integer)
        ult_b_net = db.Column(db.Integer)
        ganhos = db.Column(db.Integer)
        pt_rkg = db.Column(db.Integer)
        obs = db.Column(db.String(100))

    db.create_all()


create_db()
